#!/usr/bin/env python3
"""Cross-platform, idempotent DevOS onboarding for existing and new projects.

Default mode is read-only planning. Use --apply to create missing DevOS infrastructure.
No application source or existing semantic context is overwritten.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

CANONICAL_DEVOS = "zzpsah/chatgpt-development-os"
MINIMUM_FILES = {
    "AGENTS.md": "# Project AI Entry Point\n\nThis project uses Development OS (DevOS) portable project context.\n\nBefore substantial work: read `.ai/manifest.yaml`, `.ai/STATE-INDEX.md`, `.ai/PROJECT.md`, and `.ai/CURRENT-STATE.md`, then inspect source, tests, and Git state.\n\nRepository-local state is authoritative over AI account/chat memory.\n",
    ".ai/PROJECT.md": "# Project\n\n## Identity\n- Project ID: {project_id}\n- Name: {name}\n\n## Purpose\nDescribe what this project does and why it exists.\n\n## Scope\nDescribe capabilities and boundaries.\n",
    ".ai/CURRENT-STATE.md": "# Current State\n\nLast verified: never\n\n## Working\n-\n\n## In progress\n-\n\n## Known issues\n-\n\n## Next actions\n-\n\n## Verification\n- No verification recorded yet.\n",
    ".ai/ARCHITECTURE.md": "# Architecture\n\nDescribe components, data flows, integrations, and important boundaries.\n",
    ".ai/DECISIONS.md": "# Decisions\n\nRecord material architectural, security, data, UX, deployment, and maintenance decisions.\n",
    ".ai/TASKS.md": "# Tasks\n\n## Active\n-\n\n## Planned\n-\n\n## Blocked\n-\n\n## Completed recently\n-\n",
    ".ai/CHANGELOG.md": "# Project Change Log\n\nMaintained by Development OS automation. Records observed repository changes; Git remains authoritative for exact history. Never store secrets here.\n",
    ".ai/STATE-INDEX.md": "# Project State Index\n\nGenerated by Development OS. Deterministic repository/context evidence only; inspect source, Git, and semantic state before important conclusions.\n\n## Recovery\n1. Read `AGENTS.md` and `.ai/manifest.yaml`.\n2. Read `.ai/CURRENT-STATE.md`, `.ai/TASKS.md`, and relevant decisions/architecture.\n3. Inspect source code and Git history.\n4. Treat this index as evidence, not semantic authority.\n",
    ".ai/SESSIONS/session-template.md": "# Session — YYYY-MM-DD — Short topic\n\n## Objective\n\n## Work completed\n\n## Decisions\n\n## Verification\n\n## Open issues\n\n## Next action\n\n## Evidence\n\n## Security note\nNever record credentials, tokens, passwords, private keys, session cookies, or unnecessary personal/student data.\n",
}

GITHUB_CALLER = """# Project-side caller for the reusable Development OS context synchronizer.\nname: Development OS Context Sync\n\non:\n  push:\n    branches: [main, master]\n\npermissions:\n  contents: write\n\njobs:\n  sync:\n    uses: zzpsah/chatgpt-development-os/.github/workflows/context-sync.yml@main\n    permissions:\n      contents: write\n"""


def normalize_id(name: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return value or "project"


def load_manifest(path: Path) -> dict:
    manifest = path / ".ai" / "manifest.yaml"
    if not manifest.exists():
        return {}
    data: dict[str, str] = {}
    for line in manifest.read_text(encoding="utf-8").splitlines():
        if ":" in line and not line.startswith(" "):
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip().strip('"')
    return data


def inventory(root: Path, name: str | None, project_id: str | None) -> dict:
    if not root.exists() or not root.is_dir():
        return {"status": "HOLD", "reason": "project path does not exist or is not a directory"}
    if (root / ".git").exists():
        repository_kind = "git"
    else:
        repository_kind = "directory"

    resolved_name = name or root.name
    resolved_id = project_id or normalize_id(resolved_name)
    manifest = load_manifest(root)
    identity = "UNSET"
    if manifest:
        identity = (
            "OK" if manifest.get("managed_by") == "development-os"
            and manifest.get("canonical_repository", "").strip() != CANONICAL_DEVOS
            else "OK"
        )
        if manifest.get("managed_by") not in (None, "development-os"):
            identity = "CONFLICT"

    actions: list[dict] = []
    for rel, template in MINIMUM_FILES.items():
        target = root / rel
        if target.exists():
            actions.append({"path": rel, "action": "PRESERVE"})
        else:
            content = template.format(name=resolved_name, project_id=resolved_id)
            actions.append({"path": rel, "action": "CREATE", "content": content})

    caller = root / ".github" / "workflows" / "context-sync.yml"
    if caller.exists():
        actions.append({"path": ".github/workflows/context-sync.yml", "action": "PRESERVE"})
    elif repository_kind == "git":
        actions.append({"path": ".github/workflows/context-sync.yml", "action": "CREATE", "content": GITHUB_CALLER})

    if identity == "CONFLICT":
        return {"status": "HOLD", "reason": "existing project is managed by another framework", "name": resolved_name, "project_id": resolved_id, "repository_kind": repository_kind, "actions": actions}

    return {"status": "READY", "name": resolved_name, "project_id": resolved_id, "repository_kind": repository_kind, "actions": actions}


def apply(root: Path, report: dict) -> tuple[int, list[str]]:
    if report.get("status") != "READY":
        return 2, [f"HOLD: {report.get('reason', 'invalid onboarding state')}"]
    created: list[str] = []
    for item in report["actions"]:
        if item["action"] != "CREATE":
            continue
        target = root / item["path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(item["content"], encoding="utf-8")
        created.append(item["path"])
    return 0, created


def main() -> int:
    parser = argparse.ArgumentParser(description="Universal cross-platform DevOS project onboarding")
    parser.add_argument("--path", required=True, help="project directory")
    parser.add_argument("--name")
    parser.add_argument("--project-id")
    parser.add_argument("--apply", action="store_true", help="create missing infrastructure; default is read-only")
    parser.add_argument("--json", action="store_true", help="emit machine-readable output")
    args = parser.parse_args()

    root = Path(args.path).expanduser().resolve()
    report = inventory(root, args.name, args.project_id)
    report["mode"] = "apply" if args.apply else "plan"
    report["mutation"] = "none" if not args.apply else "missing-infrastructure-only"
    report["authority"] = "UNCHANGED"

    if args.apply:
        code, created = apply(root, report)
        report["created"] = created
        report["status"] = "ONBOARDED" if code == 0 else report.get("status", "HOLD")
    else:
        code = 0 if report.get("status") == "READY" else 2

    if args.json:
        safe = {k: v for k, v in report.items() if k != "actions"}
        safe["actions"] = [
            {k: v for k, v in item.items() if k != "content"} for item in report.get("actions", [])
        ]
        print(json.dumps(safe, indent=2, sort_keys=True))
    else:
        print("DEVOS UNIVERSAL ONBOARDING v1")
        print(f"Project: {root}")
        print(f"Project ID: {report.get('project_id', 'unknown')}")
        print(f"Mode: {'APPLY' if args.apply else 'PLAN'}")
        print("--------------------------------")
        for item in report.get("actions", []):
            print(f"{item['action']:8} {item['path']}")
        print("--------------------------------")
        if report.get("status") == "ONBOARDED":
            print("ONBOARDING STATUS: ONBOARDED")
        elif report.get("status") == "READY":
            print("ONBOARDING STATUS: READY (use --apply to create missing infrastructure)")
        else:
            print(f"ONBOARDING STATUS: HOLD — {report.get('reason', 'unknown')}")
        print("Execution authority: UNCHANGED")
        print(f"Mutation: {'missing infrastructure only' if args.apply else 'NONE'}")

    return code


if __name__ == "__main__":
    raise SystemExit(main())
