param([Parameter(Mandatory=$true,Position=0)][string]$Path,[string]$Name,[string]$ProjectId)
$ErrorActionPreference='Stop'
$root=(Resolve-Path -LiteralPath $Path -ErrorAction Stop).Path
if(-not $Name){$Name=Split-Path $root -Leaf}
if(-not $ProjectId){$ProjectId=($Name.ToLower() -replace '[^a-z0-9]+','-' -replace '(^-|-$)','')}
$ai=Join-Path $root '.ai'
$sessions=Join-Path $ai 'SESSIONS'
New-Item -ItemType Directory -Force -Path $ai,$sessions | Out-Null
function Write-IfMissing($file,$content){if(-not(Test-Path -LiteralPath $file)){Set-Content -LiteralPath $file -Value $content -Encoding UTF8}}

Write-IfMissing (Join-Path $root 'AGENTS.md') @"
# Project AI Entry Point

This project uses the Portable Project Context Specification from ChatGPT Development OS.

Before substantial work:
1. Read `.ai/manifest.yaml`.
2. Read `.ai/STATE-INDEX.md` when present for deterministic repository/context signals.
3. Read `.ai/PROJECT.md` and `.ai/CURRENT-STATE.md`.
4. Read relevant `.ai/DECISIONS.md`, `.ai/TASKS.md`, and `.ai/ARCHITECTURE.md` when present.
5. Read recent `.ai/CHANGELOG.md` and the latest relevant session record when resuming ongoing work.
6. Inspect the actual source code and tests before making changes.

During work:
- Keep facts, assumptions, decisions, and pending work distinct.
- Do not treat automated repository evidence as semantic project understanding.
- Ask for clarification only when proceeding could affect the wrong project or cause a materially wrong result.

After meaningful work:
1. Update `.ai/CURRENT-STATE.md` with verified facts.
2. Update `.ai/TASKS.md` when work changes.
3. Record important decisions in `.ai/DECISIONS.md`.
4. Record a concise session summary in `.ai/SESSIONS/` when the session changes project state or leaves important unfinished work.
5. Never store secrets, tokens, passwords, private keys, session cookies, or sensitive credentials in project context.

`.ai/STATE-INDEX.md` is generated by Development OS automation and should not be manually edited.

Do not treat AI chat history as the authoritative project state. The repository-local `.ai/` context, source code, and version-control history are the durable project record.
"@

Write-IfMissing (Join-Path $ai 'manifest.yaml') @"
context_version: 1
specification: portable-project-context
project_id: $ProjectId
name: "$Name"
managed_by: development-os
context_directory: .ai
read_first:
  - STATE-INDEX.md
  - PROJECT.md
  - CURRENT-STATE.md
recommended:
  - ARCHITECTURE.md
  - DECISIONS.md
  - TASKS.md
  - CHANGELOG.md
state_index:
  generated: true
  authority: repository-evidence-only
session_records:
  directory: SESSIONS
  format: session-template.md
secrets_policy: never-store-secrets
"@

$today=Get-Date -Format 'yyyy-MM-dd'
Write-IfMissing (Join-Path $ai 'PROJECT.md') @"
# Project

## Identity
- Project ID: $ProjectId
- Name: $Name
- Created: $today

## Purpose
Describe what this project does and why it exists.

## Scope
Describe the main capabilities and boundaries.

## Technology
- Runtime:
- Framework:
- Database:
- Hosting:

## Important constraints
- 

## Authoritative sources
- Source code
- Version-control history
- This `.ai/` directory
"@

Write-IfMissing (Join-Path $ai 'CURRENT-STATE.md') @"
# Current State

Last verified: never

## Working
- 

## In progress
- 

## Known issues
- 

## Next actions
- 

## Verification
- No verification has been recorded yet.
"@
Write-IfMissing (Join-Path $ai 'ARCHITECTURE.md') @"
# Architecture

Describe the system components, data flows, integrations, and important boundaries.

## Components
- 

## Data flow
- 

## External integrations
- 

## Operational constraints
- 
"@
Write-IfMissing (Join-Path $ai 'DECISIONS.md') @"
# Decisions

Record decisions that materially affect architecture, security, data, UX, deployment, or maintenance.

## Decision template

### DEC-YYYYMMDD-NNN
- Date:
- Status: proposed | active | superseded
- Decision:
- Context:
- Alternatives considered:
- Reason:
- Consequences:
"@
Write-IfMissing (Join-Path $ai 'TASKS.md') @"
# Tasks

## Active
- 

## Planned
- 

## Blocked
- 

## Completed recently
- 
"@
Write-IfMissing (Join-Path $ai 'CHANGELOG.md') @"
# Project Change Log

This file is maintained automatically by the Development OS GitHub context synchronizer.

It records repository evidence so a new AI can reconstruct recent activity without relying on chat history.

## Rules

- Git history remains the authoritative exact change history.
- This file is a compact AI-oriented change index, not a replacement for Git history.
- Never put secrets, credentials, private data, or source-code contents here.
- Automatic entries describe observed repository changes only; they do not assert why a change was made.
- Meaningful application changes also update `.ai/CURRENT-STATE.md` with the latest repository event.
- AI session records belong in `.ai/SESSIONS/` and may contain semantic summaries when supported by evidence.
"@
Write-IfMissing (Join-Path $ai 'STATE-INDEX.md') @"
# Project State Index

Generated automatically by Development OS.

> This file contains deterministic repository/context evidence. It is not semantic project understanding. AI must inspect `CURRENT-STATE.md`, `TASKS.md`, source code, and Git history before making important claims or decisions.

## Repository
- Branch: not yet synchronized
- HEAD: not yet synchronized
- Last commit: not yet synchronized
- Last commit date: not yet synchronized
- Last commit author: not yet synchronized

## Context health
- Overall: not yet synchronized
- `AGENTS.md`: present
- `manifest.yaml`: present
- `PROJECT.md`: present
- `CURRENT-STATE.md`: present
- `ARCHITECTURE.md`: present
- `DECISIONS.md`: present
- `TASKS.md`: present
- `CHANGELOG.md`: present
- `SESSIONS/`: present

## Task signals
- Active tasks: 0
- Planned tasks: 0
- Blocked tasks: 0

## Recent activity
- No repository synchronization has been recorded yet.

## Recovery
1. Read `AGENTS.md` and `.ai/manifest.yaml`.
2. Read `.ai/CURRENT-STATE.md`, `.ai/TASKS.md`, and relevant decisions/architecture.
3. Inspect the actual source code and Git history.
4. Treat this index as deterministic evidence, not a substitute for project understanding.
"@
Write-IfMissing (Join-Path $sessions 'session-template.md') @"
# Session — YYYY-MM-DD — Short topic

## Objective
What this session was trying to accomplish.

## Work completed
- Verified changes actually made.

## Decisions
- Decisions made during this session, with rationale when important.

## Verification
- Tests/checks actually run and their result.
- Do not claim tests passed if they were not run.

## Open issues
- Known unresolved problems or risks.

## Next action
The single most useful next step for the next AI/session.

## Evidence
- Relevant commit/PR/file references.

## Security note
Never record credentials, tokens, passwords, private keys, session cookies, or unnecessary personal/student data.
"@

Write-Host "Initialized portable AI context: $root" -ForegroundColor Green
