#!/usr/bin/env python3
"""Safely recreate deterministic DevOS derived context without touching semantic state."""
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

ROOT = Path.cwd()
CONTEXT = ROOT / os.environ.get("DEVOS_CONTEXT_DIRECTORY", ".ai")
DERIVED = {"STATE-INDEX.md", "CHANGELOG.md", "PROJECT-IDENTITY.json"}
SEMANTIC = {"PROJECT.md", "DECISIONS.md", "TASKS.md", "CURRENT-STATE.md", "ARCHITECTURE.md"}


def git(*args: str) -> str:
    return subprocess.run(("git", *args), cwd=ROOT, text=True, capture_output=True, check=True).stdout.strip()


def identity() -> dict:
    manifest = CONTEXT / "manifest.yaml"
    result: dict[str, object] = {"status": "UNKNOWN"}
    if manifest.exists():
        for line in manifest.read_text(encoding="utf-8").splitlines():
            if ":" not in line or line.startswith(" "):
                continue
            key, value = line.split(":", 1)
            result[key.strip()] = value.strip().strip("\"'")
        result["status"] = "MANIFEST_BACKED"
    return result


def write_index() -> None:
    sha = git("rev-parse", "HEAD")
    subject = git("log", "-1", "--pretty=%s")
    author = git("log", "-1", "--pretty=%an")
    date = git("log", "-1", "--date=short", "--pretty=%ad")
    branch = os.environ.get("GITHUB_REF_NAME") or git("branch", "--show-current") or "unknown"
    required = ["AGENTS.md", "manifest.yaml", "PROJECT.md", "CURRENT-STATE.md", "TASKS.md"]
    lines = [
        "# Project State Index", "", "Generated by deterministic DevOS self-healing.", "",
        "> This artifact is derived evidence only. It never overrides semantic project intent.", "",
        "## Repository",
        f"- Branch: {branch}", f"- HEAD: {sha}", f"- Last commit: {subject}",
        f"- Last commit date: {date}", f"- Last commit author: {author}", "",
        "## Context health",
    ]
    for name in required:
        path = ROOT / name if name == "AGENTS.md" else CONTEXT / name
        lines.append(f"- `{name}`: {'present' if path.exists() else 'missing'}")
    lines.extend([
        f"- `CHANGELOG.md`: {'present' if (CONTEXT / 'CHANGELOG.md').exists() else 'missing'}",
        f"- `PROJECT-IDENTITY.json`: {'present' if (CONTEXT / 'PROJECT-IDENTITY.json').exists() else 'missing'}",
        f"- `SESSIONS/`: {'present' if (CONTEXT / 'SESSIONS').exists() else 'missing'}", "",
        "## Recovery",
        "1. Read `AGENTS.md` and `.ai/manifest.yaml`.",
        "2. Read `.ai/CURRENT-STATE.md`, `.ai/TASKS.md`, and relevant decisions/architecture.",
        "3. Inspect source code and Git history.",
        "4. Treat this index as deterministic evidence only.", "",
    ])
    (CONTEXT / "STATE-INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def write_identity() -> None:
    (CONTEXT / "PROJECT-IDENTITY.json").write_text(
        json.dumps(identity(), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def write_changelog_header() -> None:
    path = CONTEXT / "CHANGELOG.md"
    if not path.exists():
        path.write_text("# Project Change Log\n\nAutomatically maintained by Development OS.\n", encoding="utf-8")


def main() -> None:
    requested = [p.strip() for p in os.environ.get("DEVOS_SELF_HEAL_FILES", "STATE-INDEX.md,CHANGELOG.md,PROJECT-IDENTITY.json").split(",") if p.strip()]
    unsafe = sorted(set(requested) - DERIVED)
    if unsafe:
        raise SystemExit(f"BLOCKED: non-derived files cannot be self-healed: {', '.join(unsafe)}")
    if set(requested) & SEMANTIC:
        raise SystemExit("BLOCKED: semantic project state is outside self-healing scope")
    CONTEXT.mkdir(parents=True, exist_ok=True)
    for name in requested:
        if name == "STATE-INDEX.md":
            write_index()
        elif name == "PROJECT-IDENTITY.json":
            write_identity()
        elif name == "CHANGELOG.md":
            write_changelog_header()
    print("HEALED:", ", ".join(requested) if requested else "none")
    print("BOUNDARY: semantic project state unchanged")


if __name__ == "__main__":
    main()
