#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / filename)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def git(project: Path, *args: str) -> str:
    return subprocess.run(["git", *args], cwd=project, check=True, text=True, capture_output=True).stdout.strip()


def main() -> None:
    policy = load("p14_policy", "adaptive-verification.py")
    executor = load("p14_executor", "adaptive-self-heal.py")

    with tempfile.TemporaryDirectory() as tmp:
        project = Path(tmp) / "managed-project"
        shutil.copytree(ROOT / "templates" / "project", project)
        git(project, "init")
        git(project, "config", "user.name", "DevOS P14 Test")
        git(project, "config", "user.email", "devos-p14@example.invalid")
        git(project, "add", ".")
        git(project, "commit", "-m", "test: initialize project")

        target = project / ".ai" / "STATE-INDEX.md"
        target.unlink()
        payload = {
            "change": {"paths": [".ai/STATE-INDEX.md"], "risk": "LOW"},
            "evidence": [{"level": "STATIC", "result": "FAIL", "observed": True, "fresh": True}],
            "repair": {"kind": "DERIVED_CONTEXT", "target": ".ai/STATE-INDEX.md", "attempts": 0, "max_attempts": 2},
        }
        before = policy.evaluate(payload)
        assert before["verification"]["status"] == "FAILED"
        assert before["healing"]["decision"] == "AUTO_ELIGIBLE"

        healed = executor.execute(project, payload)
        assert healed["status"] == "HEALED_PENDING_REVERIFY", json.dumps(healed, indent=2)
        assert healed["reverification_required"] is True
        assert target.exists()
        assert "Generated by deterministic DevOS self-healing" in target.read_text(encoding="utf-8")

        after = policy.evaluate({
            "change": {"paths": [".ai/STATE-INDEX.md"], "risk": "LOW"},
            "evidence": [{"level": "STATIC", "result": "PASS", "observed": True, "fresh": True}],
        })
        assert after["verification"]["status"] == "VERIFIED"

        semantic = executor.execute(project, {
            "change": {"paths": [".ai/CURRENT-STATE.md"], "risk": "LOW"},
            "evidence": [{"level": "STATIC", "result": "FAIL"}],
            "repair": {"kind": "DERIVED_CONTEXT", "target": ".ai/CURRENT-STATE.md"},
        })
        assert semantic["status"] == "NOT_EXECUTED"
        assert semantic["policy"]["healing"]["decision"] == "PROPOSE_ONLY"

    print("P14 deterministic healing execution + fresh re-verification: PASS")


if __name__ == "__main__":
    main()
